### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by florisvanwoudenberg** [mulian/modal-file-manager#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.13
**System**: Mac OS X 10.11
**Thrown From**: [modal-file-manager](https://github.com/mulian/modal-file-manager) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:49

TypeError: Cannot read property 'toLowerCase' of undefined
  at new Directory (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:49:39)
  at ModalFileManagerView.module.exports.ModalFileManagerView.open (/Users/floris/.atom/packages/modal-file-manager/lib/modal-file-manager-view.coffee:63:23)
  at Object.module.exports.ModalFileManager.runFileManager (/Users/floris/.atom/packages/modal-file-manager/lib/modal-file-manager.coffee:28:29)
  at atom-workspace.subscriptions.add.atom.commands.add.modal-file-manager:show (/Users/floris/.atom/packages/modal-file-manager/lib/modal-file-manager.coffee:23:91)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -0:05.0 modal-file-manager:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/floris/Localdevelopement",
    "disabledPackages": [
      "drupal-info-file",
      "language-python-django-templates",
      "language-python-django-templates",
      "language-python-django-templates",
      "language-python-django-templates",
      "language-python-django-templates",
      "language-css-plus",
      "highlight-line",
      "color-picker",
      "file-type-icons",
      "symbols-view",
      "symbols-tree-view"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.10.4
atom-ctags, v4.2.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.1
atomatigit, v1.5.4
auto-reveal-in-sidebar, v0.5.0
auto-update-packages, v1.0.0
autoclose-html, v0.19.0
autocomplete-ctags, v0.3.1
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
autocomplete-sass, v0.1.0
bezier-curve-editor, v0.7.2
code-links, v0.3.11
ctags-status, v1.3.3
docblockr, v0.7.3
docs-snippets, v0.8.0
drupal, v1.8.0
editor-settings, v1.0.4
editorconfig, v1.2.0
external-open, v0.6.1
file-icon-supplement, v0.8.3
file-icons, v1.6.9
file-types, v0.5.1
highlight-selected, v0.10.1
imdone-atom, v1.1.38
language-SCSS, v0.4.0
language-diff, v0.3.1
language-drupal, v0.4.2
language-gitignore, v0.2.0
language-liquid, v0.4.0
linter, v1.5.2
linter-handlebars, v2.1.0
linter-htmlhint, v0.1.1
linter-jsonlint, v1.0.1
linter-php, v1.0.3
linter-write-good, v0.6.1
markdown-scroll-sync, v0.4.2
modal-file-manager, v0.1.2
open-recent, v2.3.0
pdf-view, v0.23.0
php-twig, v4.0.0
pigments, v0.15.0
regex-railroad-diagram, v0.10.3
save-session, v0.15.7
set-syntax, v0.3.0
svg-preview, v0.6.1
tab-close-double-click, v1.0.1
terminal-plus, v0.4.3
tool-bar, v0.1.9
tool-bar-almighty, v0.0.3
wakatime, v4.1.0

# Dev
No dev packages
```

**Comment by mulian** [comment]
Try it again, will the last version 0.1.4 fix this issue?
